// Code generated by goctl. DO NOT EDIT.
package types

type CreateRoleReq struct {
	Nickname string `json:"nickname"`
	Sex      int32  `json:"sex"`
}

type CreateRoleResp struct {
	RoleId int64 `json:"role_id"`
}

type GetRoleInfoReq struct {
}

type GetRoleInfoResp struct {
	RoleId   int64  `json:"role_id"`
	Nickname string `json:"nickname"`
}

type LoginReq struct {
	Mobile   string `json:"mobile" validate:"len=11"`
	Password string `json:"password" validate:"min=6,max=100"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile" validate:"len=11"`
	Password string `json:"password" validate:"min=6,max=100"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type User struct {
	AccountId int64  `json:"account_id"`
	Mobile    string `json:"mobile"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserInfo User `json:"userInfo"`
}

type WXMiniAuthReq struct {
	Code          string `json:"code"`
	IV            string `json:"iv"`
	EncryptedData string `json:"encryptedData"`
}

type WXMiniAuthResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}
