// Code generated by goctl. DO NOT EDIT!

package GenRoleId

import (
    "autoGenCache/cachex"
	"context"
	"fmt"
	"github.com/zeromicro/go-zero/core/stores/cache"
)

var (
	cacheGenRoleIdUserIdPoolPrefix = "cache:GenRoleId:userIdPool"
)

type (
	// An Options is used to store the cache options.
	Options struct {
	    QueryCtxFn QueryCtxFn
	}

	// Option defines the method to customize an Options.
	Option func(o *Options)
)

type (
    // QueryCtxFn defines the query method.
	QueryCtxFn func(ctx context.Context, v any) error

	userIdPoolCache interface {
	    UpdateFromFn(ctx context.Context, getData func() (*int64, error)) (any, error)
		FindOne(ctx context.Context) (*int64, error)
		Delete(ctx context.Context) error
		SetOptions(opts ...Option)
	}

	defaultUserIdPoolCache struct {
		cachex.CachedConn
		Options
	}
)

func newUserIdPoolCache(c cache.CacheConf, opts ...cache.Option) *defaultUserIdPoolCache {
    m := &defaultUserIdPoolCache{
        CachedConn: cachex.NewConn(c, opts...),
    }
    m.SetOptions()
    return m
}

// UpdateFromFn
/** like:
	threading.GoSafe(func() {
	    ctx := context.Background()
        data, err := viewPlayerInfoCache.UpdateFromFn(ctx, func() (any, error) {
            res := "add your logic here"
            return res, nil
        })
        if err != nil {
            logx.WithContext(ctx).Error("UpdateFromFn", logx.Field("err", err))
            return
        }
        res, ok := data.(*int64)
        if !ok {
	        logx.WithContext(ctx).Errorf("UpdateFromFn expect *int64 but get %T", res)
	        return
        }
        logx.Infof("UpdateFromFn res: ", res)
    })
*/
func (m *defaultUserIdPoolCache) UpdateFromFn(ctx context.Context, getData func() (*int64, error)) (any, error) {
	data, err := m.SetCacheCtxFromFn(ctx, m.formatKey(), func() (any, error) {
        return getData()
    })
    return data, err
}

func (m *defaultUserIdPoolCache) FindOne(ctx context.Context) (*int64, error) {
	var resp int64
	key := m.formatKey()
	err := m.QueryRowCtx(ctx, &resp, key, func(ctx context.Context, v any) (err error) {
		ctx, span := cachex.StartSpan(ctx, "QueryRow")
		defer func() {
			cachex.EndSpan(span, err)
		}()
        return m.QueryCtxFn(ctx, v)
	})
	switch err {
	case nil:
		return &resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserIdPoolCache) Delete(ctx context.Context) error {
	_, err := m.ExecCtx(ctx, execDelCtxFn, m.formatKey())
	return err
}

func (m *defaultUserIdPoolCache) formatKey(args ...any) string {
	key := cacheGenRoleIdUserIdPoolPrefix
	for _, arg := range args {
		key = fmt.Sprintf("%s:%v", key, arg)
	}
	return key
}

func (m *defaultUserIdPoolCache) SetOptions(opts ...Option) {
	for _, opt := range opts {
		opt(&m.Options)
	}
	if m.QueryCtxFn == nil {
		m.QueryCtxFn = queryCtxFn
	}
}

// WithQueryCtxFn returns a func to customize an Options with given query.
func WithQueryCtxFn(query QueryCtxFn) Option {
	return func(o *Options) {
		o.QueryCtxFn = query
	}
}
