// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"zinx-zero/apps/acommon/globalkey"
)

var (
	userRoleidPoolFieldNames          = builder.RawFieldNames(&UserRoleidPool{})
	userRoleidPoolRows                = strings.Join(userRoleidPoolFieldNames, ",")
	userRoleidPoolRowsExpectAutoSet   = strings.Join(stringx.Remove(userRoleidPoolFieldNames, "`create_time`", "`update_time`"), ",")
	userRoleidPoolRowsWithPlaceHolder = strings.Join(stringx.Remove(userRoleidPoolFieldNames, "`role_id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheGamexUserRoleidPoolRoleIdPrefix = "cache:gamex:userRoleidPool:roleId:"
)

type (
	userRoleidPoolModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *UserRoleidPool) (sql.Result, error)
		FindOne(ctx context.Context, roleId int64) (*UserRoleidPool, error)
		Update(ctx context.Context, session sqlx.Session, data *UserRoleidPool) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *UserRoleidPool) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *UserRoleidPool) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*UserRoleidPool, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*UserRoleidPool, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*UserRoleidPool, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*UserRoleidPool, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*UserRoleidPool, error)
		Delete(ctx context.Context, session sqlx.Session, roleId int64) error
	}

	defaultUserRoleidPoolModel struct {
		sqlc.CachedConn
		table string
	}

	UserRoleidPool struct {
		RoleId int64 `db:"role_id"`
		IsUse  int64 `db:"is_use"`
	}
)

func newUserRoleidPoolModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserRoleidPoolModel {
	return &defaultUserRoleidPoolModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_roleid_pool`",
	}
}

func (m *defaultUserRoleidPoolModel) Insert(ctx context.Context, session sqlx.Session, data *UserRoleidPool) (sql.Result, error) {
	data.DeleteTime = time.Unix(0, 0)
	data.DelState = globalkey.Sql_DelStateNo
	gamexUserRoleidPoolRoleIdKey := fmt.Sprintf("%s%v", cacheGamexUserRoleidPoolRoleIdPrefix, data.RoleId)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, userRoleidPoolRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.RoleId, data.IsUse)
		}
		return conn.ExecCtx(ctx, query, data.RoleId, data.IsUse)
	}, gamexUserRoleidPoolRoleIdKey)
}

func (m *defaultUserRoleidPoolModel) FindOne(ctx context.Context, roleId int64) (*UserRoleidPool, error) {
	gamexUserRoleidPoolRoleIdKey := fmt.Sprintf("%s%v", cacheGamexUserRoleidPoolRoleIdPrefix, roleId)
	var resp UserRoleidPool
	err := m.QueryRowCtx(ctx, &resp, gamexUserRoleidPoolRoleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `role_id` = ? and del_state = ? limit 1", userRoleidPoolRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, roleId, globalkey.Sql_DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserRoleidPoolModel) Update(ctx context.Context, session sqlx.Session, data *UserRoleidPool) (sql.Result, error) {
	gamexUserRoleidPoolRoleIdKey := fmt.Sprintf("%s%v", cacheGamexUserRoleidPoolRoleIdPrefix, data.RoleId)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `role_id` = ?", m.table, userRoleidPoolRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.IsUse, data.RoleId)
		}
		return conn.ExecCtx(ctx, query, data.IsUse, data.RoleId)
	}, gamexUserRoleidPoolRoleIdKey)
}

func (m *defaultUserRoleidPoolModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *UserRoleidPool) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	gamexUserRoleidPoolRoleIdKey := fmt.Sprintf("%s%v", cacheGamexUserRoleidPoolRoleIdPrefix, data.RoleId)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `role_id` = ? and version = ? ", m.table, userRoleidPoolRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.IsUse, data.RoleId, oldVersion)
		}
		return conn.ExecCtx(ctx, query, data.IsUse, data.RoleId, oldVersion)
	}, gamexUserRoleidPoolRoleIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultUserRoleidPoolModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *UserRoleidPool) error {
	data.DelState = globalkey.Sql_DelStateYes
	data.DeleteTime = time.Now()
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "UserRoleidPoolModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultUserRoleidPoolModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.Sql_DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultUserRoleidPoolModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.Sql_DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultUserRoleidPoolModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*UserRoleidPool, error) {

	builder = builder.Columns(userRoleidPoolRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.Sql_DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*UserRoleidPool
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserRoleidPoolModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*UserRoleidPool, error) {

	builder = builder.Columns(userRoleidPoolRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.Sql_DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*UserRoleidPool
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserRoleidPoolModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*UserRoleidPool, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(userRoleidPoolRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.Sql_DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*UserRoleidPool
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultUserRoleidPoolModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*UserRoleidPool, error) {

	builder = builder.Columns(userRoleidPoolRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.Sql_DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*UserRoleidPool
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserRoleidPoolModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*UserRoleidPool, error) {

	builder = builder.Columns(userRoleidPoolRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.Sql_DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*UserRoleidPool
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserRoleidPoolModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultUserRoleidPoolModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultUserRoleidPoolModel) Delete(ctx context.Context, session sqlx.Session, roleId int64) error {
	gamexUserRoleidPoolRoleIdKey := fmt.Sprintf("%s%v", cacheGamexUserRoleidPoolRoleIdPrefix, roleId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `role_id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, roleId)
		}
		return conn.ExecCtx(ctx, query, roleId)
	}, gamexUserRoleidPoolRoleIdKey)
	return err
}
func (m *defaultUserRoleidPoolModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheGamexUserRoleidPoolRoleIdPrefix, primary)
}
func (m *defaultUserRoleidPoolModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `role_id` = ? and del_state = ? limit 1", userRoleidPoolRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.Sql_DelStateNo)
}

func (m *defaultUserRoleidPoolModel) tableName() string {
	return m.table
}
