// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"zinx-zero/apps/acommon/globalkey"
)

var (
	userAccountAuthFieldNames          = builder.RawFieldNames(&UserAccountAuth{})
	userAccountAuthRows                = strings.Join(userAccountAuthFieldNames, ",")
	userAccountAuthRowsExpectAutoSet   = strings.Join(stringx.Remove(userAccountAuthFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	userAccountAuthRowsWithPlaceHolder = strings.Join(stringx.Remove(userAccountAuthFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheGamexUserAccountAuthIdPrefix              = "cache:gamex:userAccountAuth:id:"
	cacheGamexUserAccountAuthAuthTypeAuthKeyPrefix = "cache:gamex:userAccountAuth:authType:authKey:"
	cacheGamexUserAccountAuthUserIdAuthTypePrefix  = "cache:gamex:userAccountAuth:userId:authType:"
)

type (
	userAccountAuthModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *UserAccountAuth) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserAccountAuth, error)
		FindOneByAuthTypeAuthKey(ctx context.Context, authType string, authKey string) (*UserAccountAuth, error)
		FindOneByUserIdAuthType(ctx context.Context, userId int64, authType string) (*UserAccountAuth, error)
		Update(ctx context.Context, session sqlx.Session, data *UserAccountAuth) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *UserAccountAuth) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *UserAccountAuth) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*UserAccountAuth, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*UserAccountAuth, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*UserAccountAuth, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*UserAccountAuth, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*UserAccountAuth, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultUserAccountAuthModel struct {
		sqlc.CachedConn
		table string
	}

	UserAccountAuth struct {
		Id         int64     `db:"id"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		DeleteTime time.Time `db:"delete_time"`
		DelState   int64     `db:"del_state"`
		Version    int64     `db:"version"` // 版本号
		UserId     int64     `db:"user_id"`
		AuthKey    string    `db:"auth_key"`  // 平台唯一id
		AuthType   string    `db:"auth_type"` // 平台类型
	}
)

func newUserAccountAuthModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserAccountAuthModel {
	return &defaultUserAccountAuthModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_account_auth`",
	}
}

func (m *defaultUserAccountAuthModel) Insert(ctx context.Context, session sqlx.Session, data *UserAccountAuth) (sql.Result, error) {
	data.DeleteTime = time.Unix(0, 0)
	data.DelState = globalkey.Sql_DelStateNo
	gamexUserAccountAuthAuthTypeAuthKeyKey := fmt.Sprintf("%s%v:%v", cacheGamexUserAccountAuthAuthTypeAuthKeyPrefix, data.AuthType, data.AuthKey)
	gamexUserAccountAuthIdKey := fmt.Sprintf("%s%v", cacheGamexUserAccountAuthIdPrefix, data.Id)
	gamexUserAccountAuthUserIdAuthTypeKey := fmt.Sprintf("%s%v:%v", cacheGamexUserAccountAuthUserIdAuthTypePrefix, data.UserId, data.AuthType)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, userAccountAuthRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.UserId, data.AuthKey, data.AuthType)
		}
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.UserId, data.AuthKey, data.AuthType)
	}, gamexUserAccountAuthAuthTypeAuthKeyKey, gamexUserAccountAuthIdKey, gamexUserAccountAuthUserIdAuthTypeKey)
}

func (m *defaultUserAccountAuthModel) FindOne(ctx context.Context, id int64) (*UserAccountAuth, error) {
	gamexUserAccountAuthIdKey := fmt.Sprintf("%s%v", cacheGamexUserAccountAuthIdPrefix, id)
	var resp UserAccountAuth
	err := m.QueryRowCtx(ctx, &resp, gamexUserAccountAuthIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", userAccountAuthRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.Sql_DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAccountAuthModel) FindOneByAuthTypeAuthKey(ctx context.Context, authType string, authKey string) (*UserAccountAuth, error) {
	gamexUserAccountAuthAuthTypeAuthKeyKey := fmt.Sprintf("%s%v:%v", cacheGamexUserAccountAuthAuthTypeAuthKeyPrefix, authType, authKey)
	var resp UserAccountAuth
	err := m.QueryRowIndexCtx(ctx, &resp, gamexUserAccountAuthAuthTypeAuthKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `auth_type` = ? and `auth_key` = ? and del_state = ? limit 1", userAccountAuthRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, authType, authKey, globalkey.Sql_DelStateNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAccountAuthModel) FindOneByUserIdAuthType(ctx context.Context, userId int64, authType string) (*UserAccountAuth, error) {
	gamexUserAccountAuthUserIdAuthTypeKey := fmt.Sprintf("%s%v:%v", cacheGamexUserAccountAuthUserIdAuthTypePrefix, userId, authType)
	var resp UserAccountAuth
	err := m.QueryRowIndexCtx(ctx, &resp, gamexUserAccountAuthUserIdAuthTypeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `auth_type` = ? and del_state = ? limit 1", userAccountAuthRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, authType, globalkey.Sql_DelStateNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAccountAuthModel) Update(ctx context.Context, session sqlx.Session, newData *UserAccountAuth) (sql.Result, error) {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return nil, err
	}
	gamexUserAccountAuthAuthTypeAuthKeyKey := fmt.Sprintf("%s%v:%v", cacheGamexUserAccountAuthAuthTypeAuthKeyPrefix, data.AuthType, data.AuthKey)
	gamexUserAccountAuthIdKey := fmt.Sprintf("%s%v", cacheGamexUserAccountAuthIdPrefix, data.Id)
	gamexUserAccountAuthUserIdAuthTypeKey := fmt.Sprintf("%s%v:%v", cacheGamexUserAccountAuthUserIdAuthTypePrefix, data.UserId, data.AuthType)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userAccountAuthRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.DeleteTime, newData.DelState, newData.Version, newData.UserId, newData.AuthKey, newData.AuthType, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.DeleteTime, newData.DelState, newData.Version, newData.UserId, newData.AuthKey, newData.AuthType, newData.Id)
	}, gamexUserAccountAuthAuthTypeAuthKeyKey, gamexUserAccountAuthIdKey, gamexUserAccountAuthUserIdAuthTypeKey)
}

func (m *defaultUserAccountAuthModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, newData *UserAccountAuth) error {

	oldVersion := newData.Version
	newData.Version += 1

	var sqlResult sql.Result
	var err error

	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}
	gamexUserAccountAuthAuthTypeAuthKeyKey := fmt.Sprintf("%s%v:%v", cacheGamexUserAccountAuthAuthTypeAuthKeyPrefix, data.AuthType, data.AuthKey)
	gamexUserAccountAuthIdKey := fmt.Sprintf("%s%v", cacheGamexUserAccountAuthIdPrefix, data.Id)
	gamexUserAccountAuthUserIdAuthTypeKey := fmt.Sprintf("%s%v:%v", cacheGamexUserAccountAuthUserIdAuthTypePrefix, data.UserId, data.AuthType)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, userAccountAuthRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.DeleteTime, newData.DelState, newData.Version, newData.UserId, newData.AuthKey, newData.AuthType, newData.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, newData.DeleteTime, newData.DelState, newData.Version, newData.UserId, newData.AuthKey, newData.AuthType, newData.Id, oldVersion)
	}, gamexUserAccountAuthAuthTypeAuthKeyKey, gamexUserAccountAuthIdKey, gamexUserAccountAuthUserIdAuthTypeKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultUserAccountAuthModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *UserAccountAuth) error {
	data.DelState = globalkey.Sql_DelStateYes
	data.DeleteTime = time.Now()
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "UserAccountAuthModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultUserAccountAuthModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.Sql_DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultUserAccountAuthModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.Sql_DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultUserAccountAuthModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*UserAccountAuth, error) {

	builder = builder.Columns(userAccountAuthRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.Sql_DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*UserAccountAuth
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserAccountAuthModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*UserAccountAuth, error) {

	builder = builder.Columns(userAccountAuthRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.Sql_DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*UserAccountAuth
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserAccountAuthModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*UserAccountAuth, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(userAccountAuthRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.Sql_DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*UserAccountAuth
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultUserAccountAuthModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*UserAccountAuth, error) {

	builder = builder.Columns(userAccountAuthRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.Sql_DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*UserAccountAuth
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserAccountAuthModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*UserAccountAuth, error) {

	builder = builder.Columns(userAccountAuthRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.Sql_DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*UserAccountAuth
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserAccountAuthModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultUserAccountAuthModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultUserAccountAuthModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	gamexUserAccountAuthAuthTypeAuthKeyKey := fmt.Sprintf("%s%v:%v", cacheGamexUserAccountAuthAuthTypeAuthKeyPrefix, data.AuthType, data.AuthKey)
	gamexUserAccountAuthIdKey := fmt.Sprintf("%s%v", cacheGamexUserAccountAuthIdPrefix, id)
	gamexUserAccountAuthUserIdAuthTypeKey := fmt.Sprintf("%s%v:%v", cacheGamexUserAccountAuthUserIdAuthTypePrefix, data.UserId, data.AuthType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, gamexUserAccountAuthAuthTypeAuthKeyKey, gamexUserAccountAuthIdKey, gamexUserAccountAuthUserIdAuthTypeKey)
	return err
}
func (m *defaultUserAccountAuthModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheGamexUserAccountAuthIdPrefix, primary)
}
func (m *defaultUserAccountAuthModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", userAccountAuthRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.Sql_DelStateNo)
}

func (m *defaultUserAccountAuthModel) tableName() string {
	return m.table
}
