// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"zinx-zero/apps/acommon/globalkey"
)

var (
	userRoleFieldNames          = builder.RawFieldNames(&UserRole{})
	userRoleRows                = strings.Join(userRoleFieldNames, ",")
	userRoleRowsExpectAutoSet   = strings.Join(stringx.Remove(userRoleFieldNames, "`create_time`", "`update_time`"), ",")
	userRoleRowsWithPlaceHolder = strings.Join(stringx.Remove(userRoleFieldNames, "`role_id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheGamexUserRoleRoleIdPrefix = "cache:gamex:userRole:roleId:"
)

type (
	userRoleModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *UserRole) (sql.Result, error)
		FindOne(ctx context.Context, roleId int64) (*UserRole, error)
		Update(ctx context.Context, session sqlx.Session, data *UserRole) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *UserRole) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *UserRole) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*UserRole, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*UserRole, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*UserRole, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*UserRole, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*UserRole, error)
		Delete(ctx context.Context, session sqlx.Session, roleId int64) error
	}

	defaultUserRoleModel struct {
		sqlc.CachedConn
		table string
	}

	UserRole struct {
		RoleId     int64     `db:"role_id"`
		AccountId  int64     `db:"account_id"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		DeleteTime time.Time `db:"delete_time"`
		DelState   int64     `db:"del_state"`
		Version    int64     `db:"version"` // 版本号
		Nickname   string    `db:"nickname"`
		Sex        int64     `db:"sex"` // 性别 0:女 1:男
	}
)

func newUserRoleModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserRoleModel {
	return &defaultUserRoleModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_role`",
	}
}

func (m *defaultUserRoleModel) Insert(ctx context.Context, session sqlx.Session, data *UserRole) (sql.Result, error) {
	data.DeleteTime = time.Unix(0, 0)
	data.DelState = globalkey.Sql_DelStateNo
	gamexUserRoleRoleIdKey := fmt.Sprintf("%s%v", cacheGamexUserRoleRoleIdPrefix, data.RoleId)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, userRoleRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.RoleId, data.AccountId, data.DeleteTime, data.DelState, data.Version, data.Nickname, data.Sex)
		}
		return conn.ExecCtx(ctx, query, data.RoleId, data.AccountId, data.DeleteTime, data.DelState, data.Version, data.Nickname, data.Sex)
	}, gamexUserRoleRoleIdKey)
}

func (m *defaultUserRoleModel) FindOne(ctx context.Context, roleId int64) (*UserRole, error) {
	gamexUserRoleRoleIdKey := fmt.Sprintf("%s%v", cacheGamexUserRoleRoleIdPrefix, roleId)
	var resp UserRole
	err := m.QueryRowCtx(ctx, &resp, gamexUserRoleRoleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `role_id` = ? and del_state = ? limit 1", userRoleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, roleId, globalkey.Sql_DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserRoleModel) Update(ctx context.Context, session sqlx.Session, data *UserRole) (sql.Result, error) {
	gamexUserRoleRoleIdKey := fmt.Sprintf("%s%v", cacheGamexUserRoleRoleIdPrefix, data.RoleId)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `role_id` = ?", m.table, userRoleRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.AccountId, data.DeleteTime, data.DelState, data.Version, data.Nickname, data.Sex, data.RoleId)
		}
		return conn.ExecCtx(ctx, query, data.AccountId, data.DeleteTime, data.DelState, data.Version, data.Nickname, data.Sex, data.RoleId)
	}, gamexUserRoleRoleIdKey)
}

func (m *defaultUserRoleModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *UserRole) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	gamexUserRoleRoleIdKey := fmt.Sprintf("%s%v", cacheGamexUserRoleRoleIdPrefix, data.RoleId)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `role_id` = ? and version = ? ", m.table, userRoleRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.AccountId, data.DeleteTime, data.DelState, data.Version, data.Nickname, data.Sex, data.RoleId, oldVersion)
		}
		return conn.ExecCtx(ctx, query, data.AccountId, data.DeleteTime, data.DelState, data.Version, data.Nickname, data.Sex, data.RoleId, oldVersion)
	}, gamexUserRoleRoleIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultUserRoleModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *UserRole) error {
	data.DelState = globalkey.Sql_DelStateYes
	data.DeleteTime = time.Now()
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "UserRoleModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultUserRoleModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.Sql_DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultUserRoleModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.Sql_DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultUserRoleModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*UserRole, error) {

	builder = builder.Columns(userRoleRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.Sql_DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*UserRole
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserRoleModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*UserRole, error) {

	builder = builder.Columns(userRoleRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.Sql_DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*UserRole
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserRoleModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*UserRole, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(userRoleRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.Sql_DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*UserRole
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultUserRoleModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*UserRole, error) {

	builder = builder.Columns(userRoleRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.Sql_DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*UserRole
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserRoleModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*UserRole, error) {

	builder = builder.Columns(userRoleRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.Sql_DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*UserRole
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserRoleModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultUserRoleModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultUserRoleModel) Delete(ctx context.Context, session sqlx.Session, roleId int64) error {
	gamexUserRoleRoleIdKey := fmt.Sprintf("%s%v", cacheGamexUserRoleRoleIdPrefix, roleId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `role_id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, roleId)
		}
		return conn.ExecCtx(ctx, query, roleId)
	}, gamexUserRoleRoleIdKey)
	return err
}
func (m *defaultUserRoleModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheGamexUserRoleRoleIdPrefix, primary)
}
func (m *defaultUserRoleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `role_id` = ? and del_state = ? limit 1", userRoleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.Sql_DelStateNo)
}

func (m *defaultUserRoleModel) tableName() string {
	return m.table
}
